### ISSUE TITLE
MIDI not playing

### ISSUE THREAD

**Issue by ashinuuu** [puppy-girl/MidiStrummer#5]
Heya! I've been using this mod for about 3-4 days now with no issues, and yesterday it just decided to stop working. I've tried re-installing it, re-installing the Midi Program, loopMIDI, GDWave, contacting the modding discord, and reaching out to other players. I'm beyond lost and confused since it was working perfectly fine at first, and now it just.. doesn't. The MIDI player plays the music perfectly fine, it just doesn't play through the game. I did switch to Hook, Line, and Sinker, but it was working fine on there too for about a day. I don't use any other mods. 
![Screenshot 2024-11-11 205620](https://github.com/user-attachments/assets/99f9dc1f-f79b-46f6-bca7-a5fc6b8ea640)

**Comment by puppy-girl** [comment]
that's weird 🤔 it shouldn't be the kind of mod that breaks and it's still working just fine for me

could you send over your gdweave.log file and, if possible, run webfishing with `start webfishing.exe` in the terminal to see if there's any midi strummer-related errors showing up? it may be another mod installed that's causing issues

**Comment by ashinuuu** [comment]
For some reason, today it's working fine. HLS just had an update today, and I cleared out all of my mods again just in case. I have no clue why it's working now, but thank you for responding!

**Comment by puppy-girl** [comment]
happy to hear its working for you now <3
